### ISSUE TITLE
cfc path unavailable on local subdirectory

### ISSUE THREAD

**Issue by m-evangelista** [gregmoser/MuraHoth#2]
Works great on live site, but locally I have my site in something like
localhost:8500/mysite.com/wwwroot/ [mura root]

The local firebug error shows a 404 for:
http://localhost:8500/plugins/Hoth/HothReportUI.cfc?method=report&exception=all&_=1323122929904"

Perhaps there is a hardcoded  "/plugins" absolute path somewhere?

**Comment by gregmoser** [comment]
Good catch, im sure there is.
