### ISSUE TITLE
suggestion - admin link w/ onAdminModuleNav

### ISSUE THREAD

**Issue by m-evangelista** [gregmoser/MuraHoth#3]
i added this little snippet to the plugin's eventhandler.cfc

```
public function onAdminModuleNav() {
    var newLinks = '<li><a href="/plugins/Hoth">Exception Tracking</a></li> ';
    return newLinks;
        }
```

obviously i am hard coding that path, which should be a variable based on the admin root, but this adds a link to the admin nav
for one-click access to the reports page. might be a nice add-on to the plugin (which rocks, btw).

**Comment by m-evangelista** [comment]
// updated - only show if logged in user is "S2" superadmin

```
public function onAdminModuleNav() {
    var newLinks = '';
    if (listFind(session.mura.memberships,'S2')){
        newLinks = '<li><a href="/plugins/Hoth">Exception Tracking</a></li>';
        }
    return newLinks;
}
```

**Comment by gregmoser** [comment]
This is awesome, can you add #application.configBean.getContext()# to the beginning of that link?  Then can you just fork the repository, make your change and submit a pull request?  If you need help getting started with git, let me know... its really easy.

**Comment by gregmoser** [comment]
This was added
